### ISSUE TITLE
[bug] いいねの位置がズレる

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/tama-river-client#16]
### バグの概要

- いいねの位置について議論がある

### 期待される動作

- pixivのスマホアプリのようにしたい。
- カードに埋め込むのではなく、relativeカードに対してabsoluteでn%n%で配置位置をz-index上に表示させて欲しいかも

### スクリーンショット

![スクリーンショット 2024-02-16 16 22 18](https://github.com/tech-creative-club/tama-river-client/assets/92194698/22b0079a-bf9c-4fe0-a6cb-fbc20fd6d99b)

**Comment by minagishl** [comment]
0ea193499ad4d287b4f578b6c875673b389e462d
